// <auto-generated />
using CompanyRelationship.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyRelationship.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20240813093729_InitialRelationship")]
    partial class InitialRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyRelationship.Model.BranchOffice", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("CompanyName");

                    b.HasIndex("CompanyName1");

                    b.ToTable("BranchOffices");
                });

            modelBuilder.Entity("CompanyRelationship.Model.BranchOfficeDept", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchOfficeName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.HasIndex("BranchOfficeName");

                    b.HasIndex("CompanyName");

                    b.ToTable("BranchOfficeDepts");
                });

            modelBuilder.Entity("CompanyRelationship.Model.Company", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CompanyRelationship.Model.BranchOffice", b =>
                {
                    b.HasOne("CompanyRelationship.Model.Company", null)
                        .WithMany("Parents")
                        .HasForeignKey("CompanyName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CompanyRelationship.Model.Company", null)
                        .WithMany("Siblings")
                        .HasForeignKey("CompanyName1");
                });

            modelBuilder.Entity("CompanyRelationship.Model.BranchOfficeDept", b =>
                {
                    b.HasOne("CompanyRelationship.Model.BranchOffice", null)
                        .WithMany("Children")
                        .HasForeignKey("BranchOfficeName")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CompanyRelationship.Model.Company", null)
                        .WithMany("Children")
                        .HasForeignKey("CompanyName");
                });

            modelBuilder.Entity("CompanyRelationship.Model.BranchOffice", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("CompanyRelationship.Model.Company", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Parents");

                    b.Navigation("Siblings");
                });
#pragma warning restore 612, 618
        }
    }
}
